// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package ent

type AuthPayload struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type NewUserInput struct {
	Email string `json:"email"`
}

type SigninInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type SignupInput struct {
	Email       string `json:"email"`
	FullName    string `json:"full_name"`
	PhoneNumber string `json:"phone_number"`
	IDCard      string `json:"id_card"`
	MemberCard  int    `json:"member_card"`
	DateOfBirth string `json:"date_of_birth"`
	Password    string `json:"password"`
}

type SignupResponse struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}
